/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   tests_integer.c                                    :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: osamoile <marvin@42.fr>                    +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2018/05/04 10:51:12 by osamoile          #+#    #+#             */
/*   Updated: 2018/05/04 10:51:13 by osamoile         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "printf.h"

void	tests_integer(void)
{
	int i = 123456;
	int j;
	int min = -2147483648;
	int max = 2147483647;
	int value;

	ft_printf("========== simple ==========\n"); j = 1;

	value = printf("%d OR: %i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %i@", j, 0); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %i@", j, 0); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %i@", j, min); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %i@", j, min); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %i@", j, max); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %i@", j, max); printf(" VALUE: %d\n", value);
	j++;
	
	ft_printf("========== width ==========\n"); j = 1;

	value = printf("%d OR: %3i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %3i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %20i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %20i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %3i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %3i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %20i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %20i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %10i@", j, 0); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %10i@", j, 0); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %20i@", j, min); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %20i@", j, min); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %20i@", j, max); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %20i@", j, max); printf(" VALUE: %d\n", value);
	j++;

	ft_printf("========== minus + width ==========\n"); j = 1;

	value = printf("%d OR: %-3i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %-3i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %-20i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %-20i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %-3i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %-3i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %-20i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %-20i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %-10i@", j, 0); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %-10i@", j, 0); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %-20i@", j, min); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %-20i@", j, min); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %-20i@", j, max); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %-20i@", j, max); printf(" VALUE: %d\n", value);
	j++;

	ft_printf("========== precision ==========\n"); j = 1;

	value = printf("%d OR: %.3i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %.3i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %.20i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %.20i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %.3i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %.3i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %.20i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %.20i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %.10i@", j, 0); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %.10i@", j, 0); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %.20i@", j, min); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %.20i@", j, min); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %.20i@", j, max); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %.20i@", j, max); printf(" VALUE: %d\n", value);
	j++;

	ft_printf("========== width + precision ==========\n"); j = 1;

	value = printf("%d OR: %1.3i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %1.3i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %1.20i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %1.20i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %3.20i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %3.20i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %10.20i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %10.20i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %20.10i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %20.10i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %20.5i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %20.5i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %20.10i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %20.10i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %20.5i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %20.5i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %1.3i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %1.3i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %1.20i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %1.20i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %3.20i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %3.20i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %10.20i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %10.20i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %5.10i@", j, 0); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %5.10i@", j, 0); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %10.5i@", j, 0); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %10.5i@", j, 0); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %10.20i@", j, min); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %10.20i@", j, min); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %20.10i@", j, min); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %20.10i@", j, min); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %10.20i@", j, max); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %10.20i@", j, max); printf(" VALUE: %d\n", value);
	j++;

	ft_printf("========== width + precision + minus ==========\n"); j = 1;

	value = printf("%d OR: %-1.3i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %-1.3i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %-1.20i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %-1.20i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %-3.20i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %-3.20i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %-10.20i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %-10.20i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %-20.10i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %-20.10i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %-20.5i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %-20.5i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %-1.3i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %-1.3i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %-1.20i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %-1.20i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %-3.20i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %-3.20i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %-10.20i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %-10.20i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %-5.10i@", j, 0); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %-5.10i@", j, 0); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %-10.5i@", j, 0); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %-10.5i@", j, 0); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %-10.20i@", j, min); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %-10.20i@", j, min); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %-20.10i@", j, min); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %-20.10i@", j, min); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %-10.20i@", j, max); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %-10.20i@", j, max); printf(" VALUE: %d\n", value);
	j++;

	ft_printf("========== plus ==========\n"); j = 1;

	value = printf("%d OR: %+i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %+i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %+i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %+i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %+i@", j, 0); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %+i@", j, 0); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %+i@", j, min); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %+i@", j, min); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %+i@", j, max); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %+i@", j, max); printf(" VALUE: %d\n", value);
	j++;

	ft_printf("========== plus + width ==========\n"); j = 1;

	value = printf("%d OR: %+3i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %+3i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %+20i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %+20i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %+3i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %+3i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %+20i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %+20i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %+10i@", j, 0); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %+10i@", j, 0); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %+20i@", j, min); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %+20i@", j, min); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %+20i@", j, max); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %+20i@", j, max); printf(" VALUE: %d\n", value);
	j++;

	ft_printf("========== plus + precision ==========\n"); j = 1;

	value = printf("%d OR: %+.3i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %+.3i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %+.20i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %+.20i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %+.3i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %+.3i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %+.20i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %+.20i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %+.10i@", j, 0); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %+.10i@", j, 0); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %+.20i@", j, min); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %+.20i@", j, min); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %+.20i@", j, max); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %+.20i@", j, max); printf(" VALUE: %d\n", value);
	j++;

	ft_printf("========== width + precision + plus ==========\n"); j = 1;

	value = printf("%d OR: %+1.3i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %+1.3i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %+1.20i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %+1.20i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %+3.20i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %+3.20i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %+10.20i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %+10.20i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %+20.10i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %+20.10i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %+20.5i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %+20.5i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %+1.3i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %+1.3i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %+1.20i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %+1.20i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %+3.20i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %+3.20i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %+10.20i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %+10.20i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %+5.10i@", j, 0); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %+5.10i@", j, 0); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %+10.5i@", j, 0); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %+10.5i@", j, 0); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %+10.20i@", j, min); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %+10.20i@", j, min); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %+20.10i@", j, min); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %+20.10i@", j, min); printf(" VALUE: %d\n", value);
	j++;

	ft_printf("========== width + precision + plus + minus ==========\n"); j = 1;

	value = printf("%d OR: %+-1.3i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %+-1.3i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %+-1.20i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %+-1.20i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %+-3.20i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %+-3.20i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %+-10.20i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %+-10.20i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %+-20.10i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %+-20.10i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %+-20.5i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %+-20.5i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %+-1.3i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %+-1.3i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %+-1.20i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %+-1.20i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %+-3.20i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %+-3.20i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %+-10.20i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %+-10.20i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %+-5.10i@", j, 0); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %+-5.10i@", j, 0); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %+-10.5i@", j, 0); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %+-10.5i@", j, 0); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %+-10.20i@", j, min); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %+-10.20i@", j, min); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %+-20.10i@", j, min); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %+-20.10i@", j, min); printf(" VALUE: %d\n", value);
	j++;

	ft_printf("========== zero + width ==========\n"); j = 1;

	value = printf("%d OR: %03i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %03i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %020i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %020i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %03i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %03i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %020i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %020i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %010i@", j, 0); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %010i@", j, 0); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %020i@", j, min); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %020i@", j, min); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %020i@", j, max); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %020i@", j, max); printf(" VALUE: %d\n", value);
	j++;

	ft_printf("========== zero + precision ==========\n"); j = 1;

	value = printf("%d OR: %0.3i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %0.3i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %0.20i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %0.20i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %0.3i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %0.3i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %0.20i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %0.20i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %0.10i@", j, 0); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %0.10i@", j, 0); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %0.20i@", j, min); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %0.20i@", j, min); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %0.20i@", j, max); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %0.20i@", j, max); printf(" VALUE: %d\n", value);
	j++;

	ft_printf("========== width + precision + zero ==========\n"); j = 1;

	value = printf("%d OR: %01.3i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %01.3i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %01.20i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %01.20i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %03.20i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %03.20i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %010.20i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %010.20i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %020.10i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %020.10i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %020.5i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %020.5i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %01.3i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %01.3i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %01.20i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %01.20i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %03.20i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %03.20i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %010.20i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %010.20i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %05.10i@", j, 0); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %05.10i@", j, 0); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %010.5i@", j, 0); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %010.5i@", j, 0); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %010.20i@", j, min); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %010.20i@", j, min); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %020.10i@", j, min); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %020.10i@", j, min); printf(" VALUE: %d\n", value);
	j++;

	ft_printf("========== width + precision + zero + minus ==========\n"); j = 1;

	value = printf("%d OR: %0-1.3i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %0-1.3i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %0-1.20i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %0-1.20i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %0-3.20i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %0-3.20i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %0-10.20i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %0-10.20i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %0-20.10i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %0-20.10i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %0-20.5i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %0-20.5i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %0-1.3i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %0-1.3i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %0-1.20i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %0-1.20i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %0-3.20i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %0-3.20i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %0-10.20i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %0-10.20i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %0-5.10i@", j, 0); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %0-5.10i@", j, 0); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %0-10.5i@", j, 0); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %0-10.5i@", j, 0); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %0-10.20i@", j, min); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %0-10.20i@", j, min); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %0-20.10i@", j, min); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %0-20.10i@", j, min); printf(" VALUE: %d\n", value);
	j++;

	ft_printf("========== width + precision + zero + plus ==========\n"); j = 1;

	value = printf("%d OR: %0+1.3i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %0+1.3i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %0+1.20i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %0+1.20i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %0+3.20i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %0+3.20i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %0+10.20i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %0+10.20i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %0+20.10i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %0+20.10i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %0+20.5i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %0+20.5i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %0+1.3i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %0+1.3i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %0+1.20i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %0+1.20i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %0+3.20i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %0+3.20i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %0+10.20i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %0+10.20i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %0+5.10i@", j, 0); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %0+5.10i@", j, 0); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %0+10.5i@", j, 0); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %0+10.5i@", j, 0); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %0+10.20i@", j, min); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %0+10.20i@", j, min); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %0+20.10i@", j, min); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %0+20.10i@", j, min); printf(" VALUE: %d\n", value);
	j++;

	ft_printf("========== width + precision + zero + plus + minus ==========\n"); j = 1;

	value = printf("%d OR: %0+-1.3i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %0+-1.3i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %0+-1.20i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %0+-1.20i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %0+-3.20i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %0+-3.20i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %0+-10.20i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %0+-10.20i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %0+-20.10i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %0+-20.10i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %0+-20.5i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %0+-20.5i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %0+-1.3i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %0+-1.3i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %0+-1.20i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %0+-1.20i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %0+-3.20i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %0+-3.20i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %0+-10.20i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %0+-10.20i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %0+-5.10i@", j, 0); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %0+-5.10i@", j, 0); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %0+-10.5i@", j, 0); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %0+-10.5i@", j, 0); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %0+-10.20i@", j, min); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %0+-10.20i@", j, min); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: %0+-20.10i@", j, min); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: %0+-20.10i@", j, min); printf(" VALUE: %d\n", value);
	j++;

	ft_printf("========== space ==========\n"); j = 1;

	value = printf("%d OR: % i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % i@", j, 0); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % i@", j, 0); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % i@", j, min); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % i@", j, min); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % i@", j, max); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % i@", j, max); printf(" VALUE: %d\n", value);
	j++;

	ft_printf("========== space + width ==========\n"); j = 1;

	value = printf("%d OR: % 3i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % 3i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % 20i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % 20i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % 3i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % 3i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % 20i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % 20i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % 10i@", j, 0); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % 10i@", j, 0); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % 20i@", j, min); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % 20i@", j, min); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % 20i@", j, max); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % 20i@", j, max); printf(" VALUE: %d\n", value);
	j++;

	ft_printf("========== space + precision ==========\n"); j = 1;

	value = printf("%d OR: % .3i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % .3i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % .20i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % .20i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % .3i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % .3i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % .20i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % .20i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % .10i@", j, 0); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % .10i@", j, 0); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % .20i@", j, min); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % .20i@", j, min); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % .20i@", j, max); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % .20i@", j, max); printf(" VALUE: %d\n", value);
	j++;

	ft_printf("========== width + precision + space ==========\n"); j = 1;

	value = printf("%d OR: % 1.3i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % 1.3i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % 1.20i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % 1.20i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % 3.20i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % 3.20i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % 10.20i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % 10.20i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % 20.10i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % 20.10i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % 20.5i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % 20.5i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % 1.3i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % 1.3i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % 1.20i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % 1.20i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % 3.20i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % 3.20i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % 10.20i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % 10.20i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % 5.10i@", j, 0); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % 5.10i@", j, 0); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % 10.5i@", j, 0); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % 10.5i@", j, 0); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % 10.20i@", j, min); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % 10.20i@", j, min); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % 20.10i@", j, min); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % 20.10i@", j, min); printf(" VALUE: %d\n", value);
	j++;

	ft_printf("========== width + precision + space + plus ==========\n"); j = 1;

	value = printf("%d OR: % +1.3i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % +1.3i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % +1.20i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % +1.20i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % +3.20i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % +3.20i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % +10.20i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % +10.20i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % +20.10i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % +20.10i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % +20.5i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % +20.5i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % +1.3i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % +1.3i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % +1.20i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % +1.20i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % +3.20i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % +3.20i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % +10.20i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % +10.20i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % +5.10i@", j, 0); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % +5.10i@", j, 0); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % +10.5i@", j, 0); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % +10.5i@", j, 0); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % +10.20i@", j, min); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % +10.20i@", j, min); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % +20.10i@", j, min); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % +20.10i@", j, min); printf(" VALUE: %d\n", value);
	j++;

	ft_printf("========== width + precision + space + plus + minus ==========\n"); j = 1;

	value = printf("%d OR: % +-1.3i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % +-1.3i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % +-1.20i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % +-1.20i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % +-3.20i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % +-3.20i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % +-10.20i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % +-10.20i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % +-20.10i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % +-20.10i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % +-20.5i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % +-20.5i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % +-1.3i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % +-1.3i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % +-1.20i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % +-1.20i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % +-3.20i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % +-3.20i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % +-10.20i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % +-10.20i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % +-5.10i@", j, 0); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % +-5.10i@", j, 0); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % +-10.5i@", j, 0); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % +-10.5i@", j, 0); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % +-10.20i@", j, min); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % +-10.20i@", j, min); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % +-20.10i@", j, min); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % +-20.10i@", j, min); printf(" VALUE: %d\n", value);
	j++;

	ft_printf("========== width + precision + space + plus + zero ==========\n"); j = 1;

	value = printf("%d OR: % +01.3i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % +01.3i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % +01.20i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % +01.20i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % +03.20i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % +03.20i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % +010.20i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % +010.20i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % +020.10i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % +020.10i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % +020.5i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % +020.5i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % +01.3i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % +01.3i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % +01.20i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % +01.20i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % +03.20i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % +03.20i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % +010.20i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % +010.20i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % +05.10i@", j, 0); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % +05.10i@", j, 0); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % +010.5i@", j, 0); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % +010.5i@", j, 0); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % +010.20i@", j, min); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % +010.20i@", j, min); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % +020.10i@", j, min); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % +020.10i@", j, min); printf(" VALUE: %d\n", value);
	j++;

	ft_printf("========== width + precision + space + plus + zero + minus ==========\n"); j = 1;

	value = printf("%d OR: % +-01.3i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % +-01.3i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % +-01.20i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % +-01.20i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % +-03.20i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % +-03.20i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % +-010.20i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % +-010.20i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % +-020.10i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % +-020.10i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % +-020.5i@", j, i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % +-020.5i@", j, i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % +-01.3i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % +-01.3i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % +-01.20i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % +-01.20i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % +-03.20i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % +-03.20i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % +-010.20i@", j, -i); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % +-010.20i@", j, -i); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % +-05.10i@", j, 0); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % +-05.10i@", j, 0); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % +-010.5i@", j, 0); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % +-010.5i@", j, 0); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % +-010.20i@", j, min); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % +-010.20i@", j, min); printf(" VALUE: %d\n", value);
	j++;
	value = printf("%d OR: % +-020.10i@", j, min); printf(" VALUE: %d\n", value);
	value = ft_printf("%d FT: % +-020.10i@", j, min); printf(" VALUE: %d\n", value);
	j++;
}
